site_name: OpenSSL Documentation
site_url: https://quarckster.github.io/openssl-docs/
repo_url: https://github.com/openssl/openssl
not_in_nav: |
  /*/internal/*
extra:
  version:
    provider: mike
    default: master
theme:
  favicon: images/favicon.ico
  name: material
  palette: 
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.suggest
    - toc.follow
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - tables
hooks:
  - hooks.py
validation:
  unrecognized_links: ignore
extra_css:
  - stylesheets/extra.css
